### ISSUE TITLE
링크 사용시 404 Notfound 발생

### ISSUE THREAD

**Issue by sangmoon** [VoiceOfEarp/books#1]
목차가 아닌 책 내용에서 

"목록으로", "이전으로" 혹은 "다음으로" 링크를 이용할 시 
404 Error 가 발생합니다.

예를 들어 ``https://voiceofearp.github.io/website/books/%EC%A0%9C%EA%B5%AD%EC%9D%98%EC%9C%84%EC%95%88%EB%B6%80/0-1-1-%EC%8B%9D%EB%AF%BC%EC%A7%80%EC%9D%98-%EC%95%84%EC%9D%B4%EB%9F%AC%EB%8B%88.html``

페이지 에서 

목록으로 가는 링크는

```html
<a href="/books/제국의위안부/">목록으로</a>
```
로 되어 있습니다. 실제 목록 페이지는
``https://voiceofearp.github.io/website/books/%EC%A0%9C%EA%B5%AD%EC%9D%98%EC%9C%84%EC%95%88%EB%B6%80/``

이지만 링크는 ''/books/제국의위안부'' 로 되어 있어 (/website/ 가 빠져있습니다) 404가 뜨는 것으로 보입니다.

모든 링크에 /website 를 추가해야 하는것이 아닌지 질문 드립니다.

**Comment by huinalam** [comment]
감사합니다. 제가 한동안 못보고 있어서 많이 늦었네요 ㅠ
해당 이슈를 해결하였습니다.
