### ISSUE TITLE
사진이 빠졌습니다.

### ISSUE THREAD

**Issue by soundlake** [VoiceOfEarp/books#5]
PDF의 부분을 캡쳐해서 올려야할 것 같은데, 어떤가요?

**Comment by huinalam** [comment]
의견 감사합니다.!
수작업으로 캡쳐하는 것도 방법인데ㅠ
PDF에서 이미지를 추출할 수 있는 방법은 없을까 싶네요.
(저도 오래전 작업이었던 지라 확인이 필요합니다.)

이전에 작업하던 스크립트를 보실 수 있습니다. (참고로 보세요.)
https://github.com/VoiceOfEarp/website/tree/master/sources/%EC%A0%9C%EA%B5%AD%EC%9D%98%EC%9C%84%EC%95%88%EB%B6%80_%EC%B1%85_%EB%B3%80%ED%99%98

**Comment by huinalam** [comment]
일부 이미지는 변환되어 추출된 것 같은데요.
[링크](https://github.com/VoiceOfEarp/website/tree/master/sources/%EC%A0%9C%EA%B5%AD%EC%9D%98%EC%9C%84%EC%95%88%EB%B6%80_%EC%B1%85_%EB%B3%80%ED%99%98/data/%EB%B0%95%EC%9C%A0%ED%95%98%20-%202015%20-%20%EC%A0%9C%EA%B5%AD%EC%9D%98%20%EC%9C%84%EC%95%88%EB%B6%80%20%E2%80%93%20%EC%8B%9D%EB%AF%BC%EC%A7%80%EC%A7%80%EB%B0%B0%EC%99%80%20%EA%B8%B0%EC%96%B5%EC%9D%98%20%ED%88%AC%EC%9F%81)

전부다 추출된건지는 확인이 필요할 것 같네요.

**Comment by soundlake** [comment]
@huinalam 본문에서 이미지는 어떻게 삽입하나요?  예를 들어, [books/제국의-위안부/1-1-1-죄와-범죄.md](https://github.com/VoiceOfEarp/books/blob/master/books/%EC%A0%9C%EA%B5%AD%EC%9D%98-%EC%9C%84%EC%95%88%EB%B6%80/1-1-1-%EC%A3%84%EC%99%80-%EB%B2%94%EC%A3%84.md) 파일의 경우, "사진1"이 삽입되어있는데, 이 사진의 absolute url ( https://voiceofearp.github.io/website/sources/%EC%A0%9C%EA%B5%AD%EC%9D%98%EC%9C%84%EC%95%88%EB%B6%80_%EC%B1%85_%EB%B3%80%ED%99%98/data/%EB%B0%95%EC%9C%A0%ED%95%98%20-%202015%20-%20%EC%A0%9C%EA%B5%AD%EC%9D%98%20%EC%9C%84%EC%95%88%EB%B6%80%20%E2%80%93%20%EC%8B%9D%EB%AF%BC%EC%A7%80%EC%A7%80%EB%B0%B0%EC%99%80%20%EA%B8%B0%EC%96%B5%EC%9D%98%20%ED%88%AC%EC%9F%81/Image_011.png )를 삽입하는 것 외에는 방법이 없을까요?

**Comment by huinalam** [comment]
사진을 넣었습니다.
아래 커밋을 참고해주세요.

https://github.com/VoiceOfEarp/books/commit/b6261658c010f9e14d3e7360c45d67474d48e9b3
