### ISSUE TITLE
문단 나눔과 줄바꿈

### ISSUE THREAD

**Issue by soundlake** [VoiceOfEarp/books#8]
일반적으로 마크다운 문법에서 더블스페이스(`  `)가 HTML의 `<br>` 태그로 변환되는 것으로 알고 있는데, 현재는 그렇지 않네요.

특히 인용문에서 문단나눔은 여러 가지 인용문이 연속적으로 인용될 때 인용문 사이를 구분하기 위해 사용되고, 하나의 인용문 안에서 문단이 나뉠 때는 줄바꿈을 사용하고 있어요. 현재까지는 이러한 줄바꿈을 위해 더블스페이스(`  `)를 사용했는데, 명시적으로 `<br>` 태그를 사용하는 것이 나을까요?

**Comment by huinalam** [comment]
현재 마크다운 변환을 파이썬 라이브러인 [markdown2](https://github.com/trentm/python-markdown2)를 활용하고 있습니다. 제가 세팅을 놓친 점이 있거나 할 것 같은데요.
당장은 명시적으로 `<br>` 태그를 넣어주시는 것도 방법일 것 같습니다.

**Comment by soundlake** [comment]
> When you *do* want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return. (https://daringfireball.net/projects/markdown/syntax#p)

제가 라인브레이크 문법을 잘못 알고 있었네요. 더블스페이스가 <br>로 변환되는 것이 아니라, trailing double space가 <br>로 변환되는 거였네요. 수정하도록 하겠습니다.

**Comment by huinalam** [comment]
이슈가 해결된 것 같아 close할게요 ^^
